const MSG_TYPE = {
  GUNSOLE_SDK_MESSAGE: "GUNSOLE_SDK_MESSAGE",
  GUNSOLE_SDK_TAB_REGISTERED: "GUNSOLE_SDK_TAB_REGISTERED",
  SDK_TO_CONTENT_SCRIPT: "SDK_TO_CONTENT_SCRIPT",
  CONTENT_SCRIPT_TO_DEVTOOLS: "CONTENT_SCRIPT_TO_DEVTOOLS",
} as const;

const MSG_SOURCE = {
  GUNSOLE_SDK: "gunsole-sdk",
  CONTENT_SCRIPT: "content-script",
} as const;

export { MSG_TYPE, MSG_SOURCE };
